const { Client } = require('pg');

function parseBoolean(value, fallback = false) {
  if (value == null) return fallback;
  const normalized = String(value).trim().toLowerCase();
  if (['1', 'true', 'yes', 'on'].includes(normalized)) return true;
  if (['0', 'false', 'no', 'off'].includes(normalized)) return false;
  return fallback;
}

function getSourceConfig() {
  const required = ['SOURCE_PGHOST', 'SOURCE_PGUSER', 'SOURCE_PGPASSWORD', 'SOURCE_PGDATABASE'];
  const missing = required.filter((k) => !process.env[k]);
  if (missing.length > 0) {
    throw new Error(
      `Missing source database env var(s): ${missing.join(', ')}. ` +
      `Set all of SOURCE_PGHOST/SOURCE_PGUSER/SOURCE_PGPASSWORD/SOURCE_PGDATABASE (and optionally SOURCE_PGPORT, SOURCE_PGSSL).`
    );
  }
  return {
    user: process.env.SOURCE_PGUSER,
    host: process.env.SOURCE_PGHOST,
    database: process.env.SOURCE_PGDATABASE,
    password: process.env.SOURCE_PGPASSWORD,
    port: Number(process.env.SOURCE_PGPORT) || 5432,
    ssl: parseBoolean(process.env.SOURCE_PGSSL, false)
      ? { rejectUnauthorized: false }
      : false,
  };
}

function getTargetConfig() {
  const connectionString =
    process.env.TARGET_DATABASE_URL ||
    process.env.SUPABASE_DB_URL ||
    process.env.DATABASE_URL;

  if (!connectionString) {
    throw new Error(
      'Missing target database connection string. Set TARGET_DATABASE_URL, SUPABASE_DB_URL, or DATABASE_URL.'
    );
  }

  const hostname = (() => {
    try {
      return new URL(connectionString).hostname;
    } catch {
      return '';
    }
  })();
  const defaultSsl = hostname && hostname !== 'localhost' && hostname !== '127.0.0.1';

  return {
    connectionString,
    ssl: parseBoolean(process.env.TARGET_PGSSL, defaultSsl)
      ? { rejectUnauthorized: false }
      : false,
  };
}

const tableDefinitions = [
  {
    name: 'agents',
    columns: ['id', 'name', 'agent_id_code', 'status', 'team', 'lob', 'campaign', 'organization_id'],
    jsonColumns: [],
    createSql: `
      CREATE TABLE IF NOT EXISTS agents (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        agent_id_code text NOT NULL,
        status text NOT NULL DEFAULT 'active',
        team text,
        lob text,
        campaign text,
        organization_id integer DEFAULT 1
      );
      CREATE UNIQUE INDEX IF NOT EXISTS agent_id_code_unique ON agents (agent_id_code);
    `,
  },
  {
    name: 'capacity_scenarios',
    columns: [
      'id', 'scenario_name', 'forecast_year', 'aht', 'hours_op', 'work_days', 'day_pcts',
      'shrinkage', 'occupancy', 'target_sl', 'asa', 'selected_week', 'created_at',
      'updated_at', 'actual_fte', 'actual_fte_start_date', 'attrition_pct', 'classes',
      'organization_id', 'channel'
    ],
    jsonColumns: ['day_pcts', 'classes'],
    createSql: `
      CREATE TABLE IF NOT EXISTS capacity_scenarios (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scenario_name varchar NOT NULL DEFAULT 'Scenario 1',
        forecast_year varchar,
        aht integer DEFAULT 320,
        hours_op integer DEFAULT 50,
        work_days integer DEFAULT 5,
        day_pcts jsonb DEFAULT '[20, 20, 20, 20, 20]'::jsonb,
        shrinkage integer DEFAULT 30,
        occupancy integer DEFAULT 85,
        target_sl integer DEFAULT 80,
        asa integer DEFAULT 20,
        selected_week integer DEFAULT 0,
        created_at timestamp without time zone DEFAULT now(),
        updated_at timestamp without time zone DEFAULT now(),
        actual_fte integer DEFAULT 0,
        actual_fte_start_date varchar DEFAULT '',
        attrition_pct double precision DEFAULT 0,
        classes jsonb DEFAULT '[]'::jsonb,
        organization_id integer DEFAULT 1,
        channel varchar DEFAULT 'voice'
      );
    `,
  },
  {
    name: 'capacity_settings',
    columns: [
      'id', 'profile_name', 'forecast_year', 'aht', 'hours_op', 'work_days',
      'shrinkage', 'occupancy', 'target_sl', 'asa', 'day_pcts', 'updated_at',
      'current_headcount', 'cost_per_fte', 'percent_of_week', 'organization_id', 'channel'
    ],
    jsonColumns: ['day_pcts'],
    createSql: `
      CREATE TABLE IF NOT EXISTS capacity_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        profile_name text NOT NULL DEFAULT 'default',
        forecast_year text,
        aht integer,
        hours_op integer,
        work_days integer,
        shrinkage numeric,
        occupancy numeric,
        target_sl numeric,
        asa integer,
        day_pcts jsonb,
        updated_at timestamp with time zone DEFAULT now(),
        current_headcount numeric,
        cost_per_fte numeric,
        percent_of_week numeric DEFAULT 100,
        organization_id integer DEFAULT 1,
        channel varchar DEFAULT 'voice'
      );
    `,
  },
  {
    name: 'forecast_ui_settings',
    columns: [
      'id', 'selected_year', 'years', 'method', 'alpha', 'beta',
      'gamma', 'updated_at', 'organization_id', 'channel'
    ],
    jsonColumns: ['years'],
    createSql: `
      CREATE TABLE IF NOT EXISTS forecast_ui_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        selected_year text,
        years jsonb,
        method text,
        alpha numeric,
        beta numeric,
        gamma numeric,
        updated_at timestamp with time zone DEFAULT now(),
        organization_id integer DEFAULT 1,
        channel varchar DEFAULT 'voice'
      );
    `,
  },
  {
    name: 'forecasts',
    columns: [
      'id', 'created_at', 'year_label', 'forecast_method', 'monthly_volumes',
      'total_volume', 'peak_volume', 'forecast_results', 'alpha', 'beta',
      'gamma', 'organization_id', 'channel'
    ],
    jsonColumns: ['monthly_volumes', 'forecast_results'],
    createSql: `
      CREATE TABLE IF NOT EXISTS forecasts (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
        year_label text,
        forecast_method text,
        monthly_volumes jsonb,
        total_volume bigint,
        peak_volume bigint,
        forecast_results jsonb,
        alpha double precision DEFAULT 0.3,
        beta double precision DEFAULT 0.1,
        gamma double precision DEFAULT 0.2,
        organization_id integer DEFAULT 1,
        channel varchar DEFAULT 'voice'
      );
      CREATE UNIQUE INDEX IF NOT EXISTS forecasts_year_label_org_channel_unique
        ON forecasts (year_label, organization_id, channel);
    `,
  },
  {
    name: 'interaction_arrival',
    columns: [
      'id', 'interval_date', 'interval_index', 'volume', 'aht',
      'updated_at', 'organization_id', 'channel'
    ],
    jsonColumns: [],
    createSql: `
      CREATE TABLE IF NOT EXISTS interaction_arrival (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        interval_date date NOT NULL,
        interval_index smallint NOT NULL,
        volume integer DEFAULT 0,
        aht double precision DEFAULT 0,
        updated_at timestamp without time zone DEFAULT now(),
        organization_id integer DEFAULT 1,
        channel varchar DEFAULT 'voice'
      );
      CREATE UNIQUE INDEX IF NOT EXISTS interaction_arrival_org_channel_unique
        ON interaction_arrival (interval_date, interval_index, organization_id, channel);
      CREATE INDEX IF NOT EXISTS idx_interaction_arrival_date
        ON interaction_arrival (interval_date);
    `,
  },
  {
    name: 'long_term_actuals',
    columns: ['id', 'year_index', 'month_index', 'volume', 'updated_at', 'organization_id', 'channel'],
    jsonColumns: [],
    createSql: `
      CREATE TABLE IF NOT EXISTS long_term_actuals (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        year_index integer NOT NULL,
        month_index integer NOT NULL,
        volume integer DEFAULT 0,
        updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
        organization_id integer DEFAULT 1,
        channel varchar DEFAULT 'voice'
      );
    `,
  },
];

function transformValue(column, value, jsonColumns) {
  if (value == null) return null;
  if (jsonColumns.includes(column)) return JSON.stringify(value);
  return value;
}

function buildUpsertSql(table) {
  const updateColumns = table.columns.filter((column) => column !== 'id');
  const conflictColumns = ['id'];

  return function upsertSqlForBatch(rowCount) {
    const valuesSql = [];
    const params = [];

    for (let rowIndex = 0; rowIndex < rowCount; rowIndex += 1) {
      const placeholderStart = rowIndex * table.columns.length;
      const placeholders = table.columns.map((_, columnIndex) => `$${placeholderStart + columnIndex + 1}`);
      valuesSql.push(`(${placeholders.join(', ')})`);
    }

    const updates = updateColumns
      .map((column) => `${column} = EXCLUDED.${column}`)
      .join(', ');

    return `
      INSERT INTO ${table.name} (${table.columns.join(', ')})
      VALUES ${valuesSql.join(',\n')}
      ON CONFLICT (${conflictColumns.join(', ')}) DO UPDATE SET
      ${updates}
    `;
  };
}

async function ensureSchema(target) {
  for (const table of tableDefinitions) {
    await target.query(table.createSql);
  }
}

async function fetchSourceRows(source, table) {
  const result = await source.query(`SELECT ${table.columns.join(', ')} FROM ${table.name} ORDER BY id ASC`);
  return result.rows;
}

async function copyTable(source, target, table) {
  const rows = await fetchSourceRows(source, table);
  const makeUpsertSql = buildUpsertSql(table);
  const batchSize = 500;

  for (let offset = 0; offset < rows.length; offset += batchSize) {
    const batch = rows.slice(offset, offset + batchSize);
    const params = batch.flatMap((row) =>
      table.columns.map((column) => transformValue(column, row[column], table.jsonColumns))
    );
    await target.query(makeUpsertSql(batch.length), params);
  }

  await target.query(
    `SELECT setval(pg_get_serial_sequence('${table.name}', 'id'), COALESCE((SELECT MAX(id) FROM ${table.name}), 1), true)`
  );

  return rows.length;
}

async function getCounts(client) {
  const counts = {};
  for (const table of tableDefinitions) {
    const result = await client.query(`SELECT count(*)::int AS count FROM ${table.name}`);
    counts[table.name] = result.rows[0].count;
  }
  return counts;
}

async function main() {
  const source = new Client(getSourceConfig());
  const target = new Client(getTargetConfig());

  try {
    await source.connect();
    await target.connect();

    console.log('Connected to source and target databases.');

    await ensureSchema(target);
    console.log('Ensured target schema exists.');

    for (const table of tableDefinitions) {
      const copied = await copyTable(source, target, table);
      console.log(`Migrated ${copied} rows into ${table.name}.`);
    }

    const sourceCounts = await getCounts(source);
    const targetCounts = await getCounts(target);

    console.log('\nRow counts after migration:');
    for (const table of tableDefinitions) {
      console.log(
        `${table.name}: source=${sourceCounts[table.name]} target=${targetCounts[table.name]}`
      );
    }
  } finally {
    await Promise.allSettled([source.end(), target.end()]);
  }
}

main().catch((error) => {
  console.error('\nMigration failed.');
  console.error(error);
  process.exit(1);
});
